Repository everycure-org/matrix, pull requests merged in 2025-08, with the labels that each got.

#1750 Refactor disease list ingestion to use pandas.CSVDataset
  pipelines/matrix/conf/base/ingestion/catalog.yml
Labels: infrastructure

#1774 Update requirements.txt with make lock
  pipelines/matrix/requirements.txt
Labels: Bugfix

#1784 Only report failure if branch name is present
  infra/modules/components/cloudbuild/slack_notifier/variable.tf
Labels: enhancement, infrastructure, alerting

#1787 Ingest EC Indication List
  pipelines/matrix/conf/base/fabricator/parameters.yml
  pipelines/matrix/conf/base/globals.yml
  pipelines/matrix/conf/base/ingestion/catalog.yml
  pipelines/matrix/conf/base/integration/catalog.yml
  pipelines/matrix/conf/base/integration/parameters.yml
  pipelines/matrix/conf/base/modelling/catalog.yml
  pipelines/matrix/conf/test/ingestion/catalog.yml
  pipelines/matrix/src/matrix/datasets/github.py
  pipelines/matrix/src/matrix/pipelines/fabricator/pipeline.py
  pipelines/matrix/src/matrix/pipelines/integration/nodes.py
  pipelines/matrix/src/matrix/pipelines/integration/pipeline.py
  pipelines/matrix/src/matrix/pipelines/integration/transformers/ec_ground_truth.py
  pipelines/matrix/src/matrix/pipelines/integration/transformers/kgml_xdtd_ground_truth.py
  pipelines/matrix/src/matrix/pipelines/modelling/pipeline.py
  pipelines/matrix/src/matrix/settings.py
Labels: Feature

#1792 Fix release history page and its generation
  docs/scripts/changelog_gen.py
  docs/src/releases/changelog_files/releases_aggregated.yaml
  docs/src/releases/changelog_files/v0.2.3_info.json
  docs/src/releases/changelog_files/v0.2.5_info.json
  docs/src/releases/changelog_files/v0.3.0_info.json
  docs/src/releases/changelog_files/v0.3.4_info.json
  docs/src/releases/changelog_files/v0.3.5_info.json
  docs/src/releases/changelog_files/v0.3.6_info.json
  docs/src/releases/changelog_files/v0.4.0_info.json
  docs/src/releases/changelog_files/v0.4.1_info.json
  docs/src/releases/changelog_files/v0.4.3_info.json
  docs/src/releases/changelog_files/v0.4.4_info.json
  docs/src/releases/changelog_files/v0.4.5_info.json
  docs/src/releases/changelog_files/v0.5.2_info.json
  docs/src/releases/changelog_files/v0.5.3_info.json
  docs/src/releases/changelog_files/v0.6.0_info.json
  docs/src/releases/changelog_files/v0.7.0_info.json
  docs/src/releases/changelog_files/v0.8.0_info.json
  docs/src/releases/changelog_files/v0.9.0_info.json
  pipelines/matrix/src/matrix/hooks.py
Labels: bug, documentation

#1796 Remove Local SSD and bumped disk size for GCP
  docs/src/pipeline/debugging/debug_memory.md
  infra/modules/stacks/compute_cluster/gke.tf
Labels: enhancement, infrastructure, cost-cutting

#1798 Bump `disk_size` of GKE Nodes to 1500 GB (1.5 TB) and disable image deletion policy
  docs/src/pipeline/debugging/debug_memory.md
  infra/modules/artifact_registry/main.tf
  infra/modules/stacks/compute_cluster/gke.tf
Labels: enhancement, infrastructure

#1800 Error creating pr for release v096 due to missing uv command
  .github/workflows/create-release-pr.yml
Labels: bug, infrastructure

#1804 Run sampling pipeline only on weekdays
  .github/workflows/scheduled-sampling-pipeline.yml
Labels: hide-from-release, Improvement

#1799 Create generic ephemeral volumes pd csi that is tied to pod
  docs/src/pipeline/debugging/debug_memory.md
  infra/modules/stacks/compute_cluster/gke.tf
  pipelines/matrix/templates/argo_wf_spec.tmpl
  pipelines/matrix/tests/test_argo.py
Labels: infrastructure
