Repository everycure-org/matrix, pull requests merged in 2025-09, with the labels that each got.

#1825 Nelson/aip 530 fix issue caused by recent changes in the code
  .github/workflows/scheduled-sampling-pipeline.yml
  .github/workflows/submit-kedro-pipeline.yml
  pipelines/matrix/tests/test_argo.py
Labels: bug, infrastructure

#1831 Nelson/aip 536 create draft pr failed because of uv not found
  .github/workflows/create-release-pr.yml
Labels: bug, infrastructure

#1870 XDATA-122 refactoring suggestion
  services/kg_dashboard/pages/_components/KnowledgeSourceFlowGraph.svelte
  services/kg_dashboard/pages/_lib/knowledge-source-flow/constants.js
  services/kg_dashboard/pages/_lib/knowledge-source-flow/data.js
  services/kg_dashboard/pages/_lib/knowledge-source-flow/layout.js
  services/kg_dashboard/pages/_lib/knowledge-source-flow/links.js
Labels: hide-from-release

#1875 Update main to reflect new baseline model using integrated KG (RTX-KG2 + ROBOKOP) embeddings
  pipelines/matrix/conf/base/filtering/parameters.yml
Labels: enhancement
